### ISSUE TITLE
Any stochastic elements to SCORPIUS reduce_dimensionality() or infer_trajectory()

### ISSUE THREAD

**Issue by lc822** [rcannood/SCORPIUS#25]
Hi,

I was wondering whether there are any stochastic elements in the `reduce_dimensionality()` or `infer_trajectory()` functions or whether I would expect these to give the same result when run multiple times on the same data?

I am asking this because I seem to be getting different results when I run my script twice with a different progression group for `draw_trajectory_plot()` which I assume is because of some stochastic effect in the `reduce_dimensionality()` or `infer_trajectory()` functions, because the progression group is not actually used for the trajectory analysis.

Best wishes,
Lucy

**Comment by rcannood** [comment]
Hi Lucy,

Yes, there are stochastic elements to the reduce dimensionality step, because it is using `lmds::lmds()` instead of regular `stats::cmdscale()` to perform MDS dimensionality reduction. If regular `cmdscale()` were to be used, the algorithm wouldn't be able to scale beyond much more than 10'000 cells. How many cells are you running it on? Increasing the number of landmarks in the `reduce_dimensionality()` function might improve robustness a tiny bit.

Kind regards,
Robrecht

**Comment by lc822** [comment]
Great thanks. Yes I have set a seed, I just wanted to know where the stochasticity came into the method.
